// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'catchgoose';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String COOCKIE_MAN = 'assets/3d/coockie-man.glb';
  static const String SANDWICH_TOAST = 'assets/3d/sandwich-toast.glb';
  static const String TOAST = 'assets/3d/toast.glb';
}
