// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'catchgoose';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String LEVEL_001 = 'assets/levels/level_001.json';
  static const String LEVEL_002 = 'assets/levels/level_002.json';
  static const String LEVEL_003 = 'assets/levels/level_003.json';
  static const String LEVEL_004 = 'assets/levels/level_004.json';
  static const String LEVEL_005 = 'assets/levels/level_005.json';
}
